package org.hov.enums;

public enum EmailType {
	EMAIL_VERIFICATION,
	EMAIL_CHANGE,
	PASSWORD_CHANGE,
	PAYMENT_PENDING,
	PAYMENT_COMPLETED,
	ORDER_PACKED,
	ORDER_DISPATCHED,
	ORDER_CANCELLED,
	ORDER_OUT_FOR_DELIVERY,
	ORDER_DELIVERED,
	ORDER_RETURN_REQUESTED,
	ORDER_RETURNED,
	ORDER_REFUNDED,
	PROMOTION_ACTIVATED,
	PROMOTION_EXPIRED
}
