package org.hov.enums;

public enum OrderStatus {
	IN_CART,
	PAID,
	ORDER_PREPARED,
	ORDER_DISPATCHED,
	ORDER_CANCELLED,
	ORDER_OUT_FOR_DELIVERY,
	ORDER_DELIVERED,
	ORDER_RETURN_REQUESTED,
	ORDER_RETURNED,
	ORDER_REFUNDED
}
